In [1]:
%matplotlib inline

In [52]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
import torch

from sklearn.datasets import load_iris

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Flatten, Dropout

# Introduction to Deep Learning. Basic Models

In [3]:
2 # scalar

2

In [4]:
[2, 3] # vector

[2, 3]

In [5]:
[
    [2, 3], 
    [4, 5]
] # 2D matrix

[[2, 3], [4, 5]]

In [6]:
# multidimensional matrix = tensor
[
    [
        [2, 3, 18],
        [2, 3, 18],
        [2, 3, 18],
        [2, 3, 18]
    ],
    [...],
    [...]
]

[[[2, 3, 18], [2, 3, 18], [2, 3, 18], [2, 3, 18]], [Ellipsis], [Ellipsis]]

In [7]:
a, b = 15, 20
print((2 * a + 3 * b) ** 2)
type((2 * a + 3 * b) ** 2)

8100


int

In [8]:
a, b = np.array([15]), np.array([20])
print((2 * a + 3 * b) ** 2)
type((2 * a + 3 * b) ** 2)

[8100]


numpy.ndarray

In [9]:
a = np.array([15, 8, -4, 3])
b = np.array([20, 3, 18, 5])
(2 * a + 3 * b) ** 2

array([8100,  625, 2116,  441])

In [10]:
a, b = tf.constant(15), tf.constant(20)
print((2 * a + 3 * b) ** 2)
type((2 * a + 3 * b) ** 2)

tf.Tensor(8100, shape=(), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [11]:
a = tf.constant([15, 8, -4, 3])
b = tf.constant([20, 3, 18, 5])
print((2 * a + 3 * b) ** 2)
((2 * a + 3 * b) ** 2).numpy()

tf.Tensor([8100  625 2116  441], shape=(4,), dtype=int32)


array([8100,  625, 2116,  441])

In [12]:
a, b = torch.tensor(15), torch.tensor(20)
print((2 * a + 3 * b) ** 2)
type((2 * a + 3 * b) ** 2)

tensor(8100)


torch.Tensor

In [13]:

print(torch.__version__)


2.5.1+cpu


__Iris dataset__

# tensorflow

In [14]:
iris_data = load_iris()

In [15]:
attributes, labels = iris_data["data"], iris_data["target"]

In [16]:
# tf.Variable(attributes)

In [17]:
attributes.shape[1] # number of features

4

In [18]:
len(set(labels)) # number of classes

3

In [19]:
# tf.keras.backend.clear_session() # save the earliar models

In [39]:
model_tf = Sequential([
    Input((attributes.shape[1],)), # input layer
    Dense(len(set(labels)), activation = "softmax") # output layer
])

In [21]:
model_tf.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 3)                   │              15 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model_tf.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

The task of NN is defined by the loss function.

In [23]:
# model_tf.fit(attributes, labels) # fit is partial fit

In [24]:
model_tf.fit(attributes, labels, batch_size = 8, epochs = 50)

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4099 - loss: 3.4562   
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4656 - loss: 2.9346 
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3982 - loss: 2.9336 
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3759 - loss: 2.8560 
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3170 - loss: 3.1183 
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3401 - loss: 2.9293 
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3405 - loss: 2.5779 
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3497 - loss: 2.6228 
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.3226 - loss: 2.5000 
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3142 - loss: 2.3443 
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.3814 - loss: 1.9762 
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy

In [25]:
model_tf.predict(attributes)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[0.48882157, 0.39331114, 0.11786736],
       [0.4800382 , 0.38059238, 0.13936949],
       [0.49410182, 0.38012046, 0.12577775],
       [0.48896658, 0.36787647, 0.14315696],
       [0.4945038 , 0.39090863, 0.11458753],
       [0.45418176, 0.42670128, 0.11911701],
       [0.4852481 , 0.38981837, 0.12493347],
       [0.4867825 , 0.3850522 , 0.12816532],
       [0.49082026, 0.36256433, 0.1466154 ],
       [0.49565446, 0.36372104, 0.14062445],
       [0.48345676, 0.40207225, 0.11447099],
       [0.49012414, 0.37446353, 0.13541242],
       [0.49794096, 0.36301744, 0.13904162],
       [0.5195584 , 0.35745752, 0.12298398],
       [0.4829765 , 0.42901888, 0.08800456],
       [0.459872  , 0.44967076, 0.09045726],
       [0.46029663, 0.44162634, 0.09807706],
       [0.47338167, 0.40816116, 0.11845715],
       [0.45808095, 0.42100078, 0.12091827],
       [0.479522  , 0.40766987, 0.1128082 ],
       [0.47067738, 0.39079395, 0.13852865],
       [0.46140543, 0.42159653, 0.11699805],
       [0.

In [26]:
tf.argmax(model_tf.predict(attributes), axis = 1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step 


<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)>

In [27]:
model_tf.evaluate(attributes, labels)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7136 - loss: 0.8000 


[0.7823010087013245, 0.6800000071525574]

# pytorch

In [28]:
attributes_pt = torch.FloatTensor(attributes)
labels_pt = torch.LongTensor(labels)

In [56]:
class LogisticRegressionPT(torch.nn.Module):
    def __init__(self):
        super(LogisticRegressionPT, self).__init__()
        self.layer = torch.nn.Linear(attributes.shape[1], len(set(labels)))
    def forward(self, x):
        x = torch.nn.functional.softmax(self.layer(x), dim = -1)
        return x

In [57]:
model_pt = LogisticRegressionPT()

In [58]:
print(model_pt)

LogisticRegressionPT(
  (layer): Linear(in_features=4, out_features=3, bias=True)
)


In [59]:
model_pt(attributes_pt)

tensor([[0.0729, 0.6520, 0.2751],
        [0.0783, 0.5744, 0.3472],
        [0.0813, 0.6170, 0.3018],
        [0.0819, 0.5803, 0.3377],
        [0.0736, 0.6666, 0.2598],
        [0.0586, 0.6752, 0.2662],
        [0.0769, 0.6348, 0.2883],
        [0.0745, 0.6269, 0.2986],
        [0.0867, 0.5592, 0.3541],
        [0.0814, 0.5829, 0.3357],
        [0.0671, 0.6712, 0.2617],
        [0.0768, 0.6169, 0.3063],
        [0.0842, 0.5777, 0.3381],
        [0.0951, 0.6089, 0.2960],
        [0.0604, 0.7384, 0.2012],
        [0.0521, 0.7589, 0.1890],
        [0.0597, 0.7127, 0.2276],
        [0.0693, 0.6493, 0.2815],
        [0.0588, 0.6628, 0.2784],
        [0.0668, 0.6832, 0.2500],
        [0.0678, 0.6050, 0.3273],
        [0.0641, 0.6662, 0.2697],
        [0.0807, 0.7024, 0.2169],
        [0.0615, 0.5788, 0.3597],
        [0.0748, 0.5850, 0.3402],
        [0.0752, 0.5520, 0.3728],
        [0.0665, 0.6101, 0.3233],
        [0.0711, 0.6419, 0.2871],
        [0.0721, 0.6369, 0.2910],
        [0.079

In [60]:
learning_rate = 0.01
criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model_pt.parameters(), lr = learning_rate)

In [61]:
def train(model_pt, optimizer, criterion, attributes, labels, num_epochs, train_losses):
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        output_train = model_pt(attributes) # forward
        loss_train = criterion(output_train, labels)
        loss_train.backward() # backward
        optimizer.step() # weight update
        train_losses[epoch] = loss_train.item()
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss_train.item():.4f}")

In [62]:
num_epochs = 50
train_losses = np.zeros(num_epochs)
train(model_pt, optimizer, criterion, attributes_pt, labels_pt, num_epochs, train_losses)

Epoch 50/50, Loss: 0.8649


In [36]:
# Logistic Regression model definition
class LogisticRegressionPT(torch.nn.Module):
    def __init__(self, input_size, num_classes):
        super(LogisticRegressionPT, self).__init__()
        self.layer = torch.nn.Linear(input_size, num_classes)
    
    def forward(self, x):
        x = self.layer(x)
        return x  # Outputs logits (not softmax for CrossEntropyLoss)

# Model setup
input_size = attributes.shape[1]  # Number of features
num_classes = len(set(labels))  # Number of unique classes in labels
model_pt = LogisticRegressionPT(input_size, num_classes)

# Training setup
learning_rate = 0.01
criterion = torch.nn.CrossEntropyLoss()  # Includes softmax internally
optimizer = torch.optim.Adam(model_pt.parameters(), lr = learning_rate)

# Training function
def train(model, optimizer, criterion, attributes, labels, num_epochs):
    train_losses = []
    for epoch in range(num_epochs):
        # Forward pass
        optimizer.zero_grad()  # Reset gradients
        outputs = model(attributes)  # Forward
        loss = criterion(outputs, labels)  # Compute loss
        
        # Backward pass
        loss.backward()  # Backpropagation
        optimizer.step()  # Update weights
        
        # Store and display loss
        train_losses.append(loss.item())
        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1}/{num_epochs}, Loss: {loss.item():.4f}")
    
    return train_losses

# Run training
num_epochs = 50
train_losses = train(model_pt, optimizer, criterion, attributes_pt, labels_pt, num_epochs)


Epoch 10/50, Loss: 0.8913
Epoch 20/50, Loss: 0.8454
Epoch 30/50, Loss: 0.7238
Epoch 40/50, Loss: 0.6783
Epoch 50/50, Loss: 0.6322


In [37]:
print(torch.__version__)

2.5.1+cpu


__Many layers in pythorch__

In [38]:
class LogisticRegressionPT(torch.nn.Module):
    def __init__(self):
        super(LogisticRegressionPT, self).__init__()
        self.layer1 = torch.nn.Linear(attributes.shape[1], 20)
        self.layer2 = torch.nn.Linear(20, 15)
        self.layer3 = torch.nn.Linear(15, 10)
        self.layer4 = torch.nn.Linear(10, len(set(labels)))
    def forward(self, x):
        x = torch.nn.functional.relu(self.layer1(x))
        x = torch.nn.functional.relu(self.layer2(x))
        x = torch.nn.functional.relu(self.layer3(x))
        x = torch.nn.functional.softmax(self.layer4(x))
        return x

__Many layers in Tensorflow__

In [41]:
model_tf_multilayer = Sequential([
    Input((attributes.shape[1],)), # input layer
    Dense(20, activation = "relu"), 
    Dense(15, activation = "relu"),
    Dense(15, activation = "relu"),
    Dense(len(set(labels)), activation = "softmax") # output layer
])

In [42]:
model_tf_multilayer.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 20)                  │             100 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 15)                  │             315 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 15)                  │             240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 3)                   │              48 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 703 (2.75 KB)

 Trainable params: 703 (2.75 KB)

 Non-trainable params: 0 (0.00 B)

In [43]:
model_tf_multilayer.compile(loss = "sparse_categorical_crossentropy", optimizer = "adam", metrics = ["accuracy"])

In [44]:
model_tf_multilayer.fit(attributes, labels, batch_size = 8, epochs = 50)

Epoch 1/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2667 - loss: 1.2653
Epoch 2/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2375 - loss: 1.1421 
Epoch 3/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2791 - loss: 1.0922 
Epoch 4/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3651 - loss: 1.0590 
Epoch 5/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4571 - loss: 1.0089 
Epoch 6/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3491 - loss: 0.9728 
Epoch 7/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3652 - loss: 0.8920 
Epoch 8/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4276 - loss: 0.8483 
Epoch 9/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5038 - loss: 0.7993 
Epoch 10/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8570 - loss: 0.7660 
Epoch 11/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9578 - loss: 0.7142 
Epoch 12/50
19/19 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0

In [45]:
model_tf_multilayer.predict(attributes)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step


array([[9.98398244e-01, 1.60179078e-03, 1.71562675e-08],
       [9.95978355e-01, 4.02149931e-03, 9.61487672e-08],
       [9.97444749e-01, 2.55508930e-03, 6.22665439e-08],
       [9.95613456e-01, 4.38644271e-03, 1.77172296e-07],
       [9.98504519e-01, 1.49546238e-03, 1.78057640e-08],
       [9.98498559e-01, 1.50141679e-03, 1.20843655e-08],
       [9.97389019e-01, 2.61088763e-03, 8.12331606e-08],
       [9.97749507e-01, 2.25050189e-03, 3.52778073e-08],
       [9.94508088e-01, 5.49161574e-03, 3.26220203e-07],
       [9.96552944e-01, 3.44693032e-03, 7.41828003e-08],
       [9.98789608e-01, 1.21036929e-03, 7.35684713e-09],
       [9.97048318e-01, 2.95157847e-03, 7.52746701e-08],
       [9.96567607e-01, 3.43230669e-03, 8.42048209e-08],
       [9.97110307e-01, 2.88961688e-03, 1.20174164e-07],
       [9.99543965e-01, 4.55972389e-04, 7.01479486e-10],
       [9.99428570e-01, 5.71421580e-04, 1.34125500e-09],
       [9.99155402e-01, 8.44656082e-04, 3.98885458e-09],
       [9.98290002e-01, 1.70994

In [46]:
tf.argmax(model_tf_multilayer.predict(attributes), axis = 1)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step 


<tf.Tensor: shape=(150,), dtype=int64, numpy=
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)>

In [47]:
model_tf_multilayer.evaluate(attributes, labels)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9925 - loss: 0.0463  


[0.07683354616165161, 0.9866666793823242]

A deeper model is trained faster.

Using wrong activation function (e.g. than instead of softmax) we will obtain wrong results (random classification).

__Comparing numbers__

In [67]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [68]:
model = Sequential([
    Flatten(),
    Dense(512, activation = "relu"),
    Dropout(0.2),
    Dense(10, activation = "softmax")
])

In [69]:
model.compile(
    optimizer = "adam",
    loss = "sparse_categorical_crossentropy",
    metrics = ["accuracy"]
)

In [70]:
model.fit(x_train, y_train, epochs = 10)
model.evaluate(x_test, y_test)

Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8907 - loss: 0.3681
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9707 - loss: 0.0978
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9787 - loss: 0.0675
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9852 - loss: 0.0475
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9879 - loss: 0.0364
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9887 - loss: 0.0331
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9914 - loss: 0.0269
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9919 - loss: 0.0243
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9937 - loss: 0.0190
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9927 - loss: 0.0216
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9781 - loss: 0.0861


[0.07282503694295883, 0.9818000197410583]